### PR TITLE
Fallback to api login when a captcha is required.

### PR DESCRIPTION
**Pull request by AlecsFerra**
Sometimes when a new device is used the api require the client to solve
a captcha, since is a stupid idea we ignore the captcha and we try to
login using the api key, after the first login the api should not ask
again for the captcha.

This should solve #31

### CODE REVIEW

**Comment by AlecsFerra** [comment]
I don't have access to the test accounts.

**Review by mvdan — COMMENTED** [review]
I've just emailed the test account passwords to alecsferra@protonmail.com :) Note that CI only uses those secrets for pushes to branches on the main repository, so even though CI is green on your PR, it skipped those tests as it's a job from a third party fork.

**Comment by AlecsFerra** [comment]
bump

**Review by mvdan — APPROVED** [review]
Thanks! I trust that you already used the secrets I emailed you to end-to-end test this, but we can also see the CI run once this hits master. Master is broken right now, anyway :)

**Comment by mvdan** [comment]
Master still fails for the same reason as it did before: the bitwarden API just times out after ten seconds. I really don't understand what's up with that. It started happening about a year ago, so perhaps they somehow banned or rate-limited GitHub's IPs.

**Pull request merged**
