### PR TITLE
Fix reading apiurl/identyurl from configuration.

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by mvdan** [comment]
I think the CI failures are because the secrets aren't available to PRs. I'll take a look.

**Comment by mvdan** [comment]
Sorry, but I'll have to revert the ini config commit. I've confirmed that it was the cause of the failures. See `testdata/scripts/config.txt`; the keys aren't case insensitive.

Of course, we could make them case insensitive if we really want. I'm not sure what's most common with ini files. But such a change would need to make sure the tests aren't broken.

**Comment by Mic92** [comment]
They were case-sensitive on my system. Without the patch I cannot set `apiurl` or `identityurl`. The tests must be incorrect. This is my configuration:

```
email = joerg@higgsboson.tk
apiURL = https://bitwarden.thalheim.io/api
identityURL = https://bitwarden.thalheim.io/identity
```

**Comment by mvdan** [comment]
OK, I see what you're saying now. The tests don't cover this scenario, because the user/password is always supplied via env vars. There's indeed a bug here.

**Comment by mvdan** [comment]
@Mic92 that bug should now be fixed, and I've adapted the tests to still pass.

**Pull request merged**
